// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
const spec_Identifier = {__proto__:null,true:8, false:10, def:12, var:14, val:16, if:18, else:20, return:22, throw:24}
export const parser = LRParser.deserialize({
  version: 14,
  states: "!pQYQPOOO!TQPO'#ClO![QPO'#CoOOQO'#Ct'#CtOOQO'#Cp'#CpQYQPOOOOQO,59W,59WO!cQPO,59WOOQO,59Z,59ZO!jQPO,59ZOOQO-E6n-E6nOOQO1G.r1G.rOOQO1G.u1G.u",
  stateData: "!q~OgOSPOS~ORROSROTROUROVROWROXROYROZRO[RO]RO_PObQO~O^UO~PYOaWO~PYO^ZO~PYOa[O~PYO",
  goto: "!YiPPPPPPPPPPPPPPPPjPPjrPPP!Q]ROPQTVXQTOQVPQXQVYTVX]SOPQTVX",
  nodeNames: "⚠ LineComment Program Identifier true false def var val if else return throw String ) ( Application ] [ Application",
  maxTerm: 24,
  nodeProps: [
    ["openedBy", 14,"(",17,"["],
    ["closedBy", 15,")",18,"]"]
  ],
  skippedNodes: [0,1],
  repeatNodeCount: 1,
  tokenData: "%b~R^XY}YZ}]^}pq}rs!`xy#|yz$R!P!Q$W!Q![$u!c!}$u!}#O%W#P#Q%]#R#S$u#T#o$u~!SSg~XY}YZ}]^}pq}~!cVOr!`rs!xs#O!`#O#P!}#P;'S!`;'S;=`#v<%lO!`~!}O]~~#QRO;'S!`;'S;=`#Z;=`O!`~#^WOr!`rs!xs#O!`#O#P!}#P;'S!`;'S;=`#v;=`<%l!`<%lO!`~#yP;=`<%l!`~$RO_~~$WO^~~$ZP!P!Q$^~$cSP~OY$^Z;'S$^;'S;=`$o<%lO$^~$rP;=`<%l$^~$zSR~!Q![$u!c!}$u#R#S$u#T#o$u~%]Ob~~%bOa~",
  tokenizers: [0],
  topRules: {"Program":[0,2]},
  specialized: [{term: 3, get: (value) => spec_Identifier[value] || -1}],
  tokenPrec: 0
})

