// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
const spec_Identifier = {__proto__:null,def:8, fun:10, let:12, mutable:14, if:16, cond:18, while:20, block:22}
export const parser = LRParser.deserialize({
  version: 14,
  states: "#YQYQPOOO!mQPO'#CsO!tQPO'#CvO!{QPO'#CyOOQO'#DO'#DOOOQO'#Cz'#CzQYQPOOOOQO,59_,59_O#SQPO,59_OOQO,59b,59bO#ZQPO,59bOOQO,59e,59eO#bQPO,59eOOQO-E6x-E6xOOQO1G.y1G.yOOQO1G.|1G.|OOQO1G/P1G/P",
  stateData: "#p~OqOSPOS~ORSOSSOTSOUSOVSOWSOXSOYSOZSO[SO]SO^SO_SO`SOaSObSOcSOdSOfPOiQOlRO~OeVO~PYOhXO~PYOkZO~PYOe^O~PYOh_O~PYOk`O~PYOP^ab`a~",
  goto: "!lsPPPPPPPPPPPPPPPPPPPPPPPtPPtPPt!OPPP!baSOPQRUWY[QUOQWPQYQQ[RX]UWY[aTOPQRUWY[",
  nodeNames: "⚠ LineComment Program Identifier def fun let mutable if cond while block Literal Keyword Number String Operator Bar Colon Comma Semicolon ) ( Application ] [ Application } { Application",
  maxTerm: 34,
  nodeProps: [
    ["openedBy", 21,"(",24,"[",27,"{"],
    ["closedBy", 22,")",25,"]",28,"}"]
  ],
  skippedNodes: [0,1],
  repeatNodeCount: 1,
  tokenData: ".j~RoXY#SYZ#S]^#Spq#Sqr#ers$`st%|vw#exy&byz&gz{#e{|#e|}&l}!O#e!O!P&q!P!Q(T!Q!['o![!]+V!]!^,S!^!_#e!_!`#e!`!a#e!c!},X!}#O,j#P#Q,o#R#S,X#T#o,X#o#p,t#p#q,y#q#r-v#r#s-{~#XSq~XY#SYZ#S]^#Spq#S~#j[`~qr#evw#ez{#e{|#e}!O#e!O!P#e!P!Q#e![!]#e!^!_#e!_!`#e!`!a#e#p#q#e~$cVOr$`rs$xs#O$`#O#P$}#P;'S$`;'S;=`%v<%lO$`~$}O_~~%QRO;'S$`;'S;=`%Z;=`O$`~%^WOr$`rs$xs#O$`#O#P$}#P;'S$`;'S;=`%v;=`<%l$`<%lO$`~%yP;=`<%l$`~&PQ!c!}&V#T#o&V~&[Q[~!c!}&V#T#o&V~&gOf~~&lOe~~&qOc~~&v]`~qr#evw#ez{#e{|#e}!O#e!O!P#e!P!Q#e!Q!['o![!]#e!^!_#e!_!`#e!`!a#e#p#q#e~'tT^~!O!P'o!Q!['o!c!}'o#R#S'o#T#o'o~(Y[`~qr#evw#ez{#e{|#e}!O#e!O!P#e!P!Q)O![!]#e!^!_#e!_!`#e!`!a#e#p#q#e~)VgP~`~OY*nZq*nqr)Orv*nvw)Owz*nz{)O{|)O|}*n}!O)O!O!P)O!P!Q)O!Q![*n![!])O!]!^*n!^!_)O!_!`)O!`!a)O!a#p*n#p#q)O#q;'S*n;'S;=`+P<%lO*n~*sSP~OY*nZ;'S*n;'S;=`+P<%lO*n~+SP;=`<%l*n~+^[b~`~qr#evw#ez{#e{|#e}!O#e!O!P#e!P!Q#e![!]#e!^!_#e!_!`#e!`!a#e#p#q#e~,XOd~~,^SR~!Q![,X!c!},X#R#S,X#T#o,X~,oOi~~,tOh~~,yOl~~-Q[a~`~qr#evw#ez{#e{|#e}!O#e!O!P#e!P!Q#e![!]#e!^!_#e!_!`#e!`!a#e#p#q#e~-{Ok~~.OR!c!}.X#R#S.X#T#o.X~.^S]~!Q![.X!c!}.X#R#S.X#T#o.X",
  tokenizers: [0],
  topRules: {"Program":[0,2]},
  specialized: [{term: 3, get: (value) => spec_Identifier[value] || -1}],
  tokenPrec: 117
})

