// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
const spec_Identifier = {__proto__:null,true:8, false:10, let:12, fun:14, if:16, else:18, return:20, while:22, raise:24, lam:26, end:28, vec:30}
export const parser = LRParser.deserialize({
  version: 14,
  states: "!pQYQPOOO!^QPO'#CoO!eQPO'#CrOOQO'#Cw'#CwOOQO'#Cs'#CsQYQPOOOOQO,59Z,59ZO!lQPO,59ZOOQO,59^,59^O!sQPO,59^OOQO-E6q-E6qOOQO1G.u1G.uOOQO1G.x1G.x",
  stateData: "!z~OjOSPOS~ORROSROTROUROVROWROXROYROZRO[RO]RO^RO_RO`RObPOeQO~OaUO~PYOdWO~PYOaZO~PYOd[O~PYO",
  goto: "!]lPPPPPPPPPPPPPPPPPPPmPPmuPPP!T]ROPQTVXQTOQVPQXQVYTVX]SOPQTVX",
  nodeNames: "⚠ LineComment Program Identifier true false let fun if else return while raise lam end vec String ) ( Application ] [ Application",
  maxTerm: 27,
  nodeProps: [
    ["openedBy", 17,"(",20,"["],
    ["closedBy", 18,")",21,"]"]
  ],
  skippedNodes: [0,1],
  repeatNodeCount: 1,
  tokenData: "%b~R^XY}YZ}]^}pq}rs!`xy#|yz$R!P!Q$W!Q![$u!c!}$u!}#O%W#P#Q%]#R#S$u#T#o$u~!SSj~XY}YZ}]^}pq}~!cVOr!`rs!xs#O!`#O#P!}#P;'S!`;'S;=`#v<%lO!`~!}O`~~#QRO;'S!`;'S;=`#Z;=`O!`~#^WOr!`rs!xs#O!`#O#P!}#P;'S!`;'S;=`#v;=`<%l!`<%lO!`~#yP;=`<%l!`~$ROb~~$WOa~~$ZP!P!Q$^~$cSP~OY$^Z;'S$^;'S;=`$o<%lO$^~$rP;=`<%l$^~$zSR~!Q![$u!c!}$u#R#S$u#T#o$u~%]Oe~~%bOd~",
  tokenizers: [0],
  topRules: {"Program":[0,2]},
  specialized: [{term: 3, get: (value) => spec_Identifier[value] || -1}],
  tokenPrec: 0
})

