// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
const spec_Identifier = {__proto__:null,true:8, false:10, let:12, fun:14, if:16, else:18, begin:20, return:22, while:24, raise:26, lam:28, end:30, vec:32}
export const parser = LRParser.deserialize({
  version: 14,
  states: "!pQYQPOOO!aQPO'#CpO!hQPO'#CsOOQO'#Cx'#CxOOQO'#Ct'#CtQYQPOOOOQO,59[,59[O!oQPO,59[OOQO,59_,59_O!vQPO,59_OOQO-E6r-E6rOOQO1G.v1G.vOOQO1G.y1G.y",
  stateData: "!}~OkOSPOS~ORROSROTROUROVROWROXROYROZRO[RO]RO^RO_RO`ROaROcPOfQO~ObUO~PYOeWO~PYObZO~PYOe[O~PYO",
  goto: "!^mPPPPPPPPPPPPPPPPPPPPnPPnvPPP!U]ROPQTVXQTOQVPQXQVYTVX]SOPQTVX",
  nodeNames: "⚠ LineComment Program Identifier true false let fun if else begin return while raise lam end vec String ) ( Application ] [ Application",
  maxTerm: 28,
  nodeProps: [
    ["openedBy", 18,"(",21,"["],
    ["closedBy", 19,")",22,"]"]
  ],
  skippedNodes: [0,1],
  repeatNodeCount: 1,
  tokenData: "%b~R^XY}YZ}]^}pq}rs!`xy#|yz$R!P!Q$W!Q![$u!c!}$u!}#O%W#P#Q%]#R#S$u#T#o$u~!SSk~XY}YZ}]^}pq}~!cVOr!`rs!xs#O!`#O#P!}#P;'S!`;'S;=`#v<%lO!`~!}Oa~~#QRO;'S!`;'S;=`#Z;=`O!`~#^WOr!`rs!xs#O!`#O#P!}#P;'S!`;'S;=`#v;=`<%l!`<%lO!`~#yP;=`<%l!`~$ROc~~$WOb~~$ZP!P!Q$^~$cSP~OY$^Z;'S$^;'S;=`$o<%lO$^~$rP;=`<%l$^~$zSR~!Q![$u!c!}$u#R#S$u#T#o$u~%]Of~~%bOe~",
  tokenizers: [0],
  topRules: {"Program":[0,2]},
  specialized: [{term: 3, get: (value) => spec_Identifier[value] || -1}],
  tokenPrec: 0
})

